spring.profiles.active=${PROFILE:dev}

# File upload limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-http-form-post-size=100MB

# Email for service-to-service communication with GreenCityUser
spring.liquibase.parameters.service-email=service@greencity.ua

greencity.authorization.googleApiKey=${GOOGLE_API_KEY:default-key}

# Swagger configuration
springdoc.paths-to-match=/**
springdoc.paths-to-exclude=/management/**
springdoc.packages-to-scan=greencity.controller
springdoc.swagger-ui.doc-expansion=none
spring.jpa.open-in-view=true
# Google Oauth 2.0 data
#TODO store id and secret as env variables
#TODO add google account credentials to a common source
#TODO ask about layered architecture approach pom files workflow
#
#
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
# Google OAuth2 Client Registration
spring.security.oauth2.client.provider.google.authorization-uri=[https://accounts.google.com/o/oauth2/auth](https://accounts.google.com/o/oauth2/auth)
spring.security.oauth2.client.provider.google.token-uri=[https://oauth2.googleapis.com/token](https://oauth2.googleapis.com/token)
spring.security.oauth2.client.provider.google.user-info-uri=[https://www.googleapis.com/oauth2/v2/userinfo](https://www.googleapis.com/oauth2/v2/userinfo)
spring.security.oauth2.client.provider.google.user-name-attribute=email
# Security settings
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true