TWO_USERS={user1} and {user2}
THREE_OR_MORE_USERS={user1}, {user2} and other users

ECONEWS_COMMENT_TITLE=News comment
ECONEWS_COMMENT={user} commented on your news Â«{secondMessage}Â».

EVENT_EDITED_TITLE=Event updated
EVENT_EDITED={user} updated the event «{secondMessage}».
