TWO_USERS={user1} and {user2}
THREE_OR_MORE_USERS={user1}, {user2} and other users

ECONEWS_COMMENT_TITLE=News comment
ECONEWS_COMMENT={user} commented on your news «{secondMessage}».

EVENT_COMMENT_TITLE=Event comment
EVENT_COMMENT={user} commented on your event «{secondMessage}».

HABIT_COMMENT_TITLE=Habit comment
HABIT_COMMENT={user} commented on your habit «{secondMessage}».

EVENT_LIKE_TITLE=Event like
EVENT_LIKE={user} liked your event «{secondMessage}».

HABIT_LIKE_TITLE=Habit like
HABIT_LIKE={user} liked your habit «{secondMessage}».

EVENT_EDITED_TITLE=Event updated
EVENT_EDITED={user} updated the event �{secondMessage}�.
